const initialState = {
  properties : [
    {
      id: 1,
      name: 'Mieszkanie w centrum Katowic',
      type: 'mieszkanie',
      purpose: 'sprzedaż',
      city: 'Katowice',
      district: 'Centrum',
      description:"Dwupokojowe mieszaknie na drugim piętrze czteropiętrowego bloku i jakies inne pierdoły",
    },
    {
      id: 2,
      name: 'Dom w sercu Nikiszowca',
      type: 'dom',
      purpose: 'wynajem',
      city: 'Katowice',
      district: 'Nikiszowiec',
      description:"Piękny dom na Nikiszowcu z blefnsndas csahdiasd ashdioasxdasn",
    },
    {
      id: 3,
      name: 'Mieskzanie na zadupiu',
      type: 'mieszkanie',
      purpose: 'wynajem',
      city: 'Sosnowiec',
      district: 'Centrum',
      description:"W samym srodku niczego mieskzanie djsdkasmcasasm xasnjcbasklx snxianskxmas",
    },
    {
      id: 4,
      name: 'Mieszkanie na Batorym',
      type: 'mieszkanie',
      purpose: 'sprzedaż',
      city: 'Chorzów',
      district: 'Batory',
      description:"Dla odwaznych mieskzanie na Batorym bcsda c scsioc cnsijaso nsiasmoxa",
    },
    {
      id: 5,
      name: 'Działka Katowice - Wełnowiec',
      type: 'działka',
      purpose: 'sprzedaż',
      city: 'Katowice',
      district: 'Wełnowiec',
      description:"Kawałek ziemi w nieciekawej okolicy csdhcias csniasnc ascxiasnx asxnasixna",
    },
    {
    id: 6,
      name: 'Miekszanie w kamienicy',
      type: 'mieszkanie',
      purpose: 'wynajem',
      city: 'Katowice',
      district: 'Centrum',
      description:"Mieszkanie w kamienicy w centrum  kasuasda sbasdas sakbdasd",
    },
    {
    id: 7,
      name: 'Miekszanie w ładnej okolicy',
      type: 'mieszkanie',
      purpose: 'wynajem',
      city: 'Sosnowiec',
      district: 'Centrum',
      description:"Mieszkanie w kamienicy w centrum  kasuasda sbasdas sakbdasd",
    },
    {
    id: 8,
      name: 'Miekszanie jakies tam',
      type: 'mieszkanie',
      purpose: 'sprzedaż',
      city: 'Katowice',
      district: 'Centrum',
      description:"Mieszkanie w cdssdffsdv vsdvsd fsdf sdf  fsdf ds fsd fsdsd",
    },
    {
    id: 9,
      name: 'Dom stary',
      type: 'dom',
      purpose: 'wynajem',
      city: 'Katowice',
      district: 'Nikiszowiec',
      description:"Dom w dasdasdvsd dasdas dasdas  kasuasda sbasdas sakbdasd",
    },
    {
    id: 10,
      name: 'Miekszanie takie śmakie',
      type: 'mieszkanie',
      purpose: 'sprzedaż',
      city: 'Katowice',
      district: 'Centrum',
      description:"Mieszkanie w kamienicy w centrum  kasuasda sbasdas sakbdasd",
    },  
  ]
};

export default initialState;